# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/oneionei/MyProjects/rubbicx/rubikx-3d

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/oneionei/MyProjects/rubbicx/rubikx-3d

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/oneionei/MyProjects/rubbicx/rubikx-3d/CMakeFiles /Users/oneionei/MyProjects/rubbicx/rubikx-3d//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/oneionei/MyProjects/rubbicx/rubikx-3d/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RubikX3D

# Build rule for target.
RubikX3D: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RubikX3D
.PHONY : RubikX3D

# fast build rule for target.
RubikX3D/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/build
.PHONY : RubikX3D/fast

src/Animation.o: src/Animation.cpp.o
.PHONY : src/Animation.o

# target to build an object file
src/Animation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/Animation.cpp.o
.PHONY : src/Animation.cpp.o

src/Animation.i: src/Animation.cpp.i
.PHONY : src/Animation.i

# target to preprocess a source file
src/Animation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/Animation.cpp.i
.PHONY : src/Animation.cpp.i

src/Animation.s: src/Animation.cpp.s
.PHONY : src/Animation.s

# target to generate assembly for a file
src/Animation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/Animation.cpp.s
.PHONY : src/Animation.cpp.s

src/Camera.o: src/Camera.cpp.o
.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i
.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s
.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/Colors.o: src/Colors.cpp.o
.PHONY : src/Colors.o

# target to build an object file
src/Colors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/Colors.cpp.o
.PHONY : src/Colors.cpp.o

src/Colors.i: src/Colors.cpp.i
.PHONY : src/Colors.i

# target to preprocess a source file
src/Colors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/Colors.cpp.i
.PHONY : src/Colors.cpp.i

src/Colors.s: src/Colors.cpp.s
.PHONY : src/Colors.s

# target to generate assembly for a file
src/Colors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/Colors.cpp.s
.PHONY : src/Colors.cpp.s

src/Lighting.o: src/Lighting.cpp.o
.PHONY : src/Lighting.o

# target to build an object file
src/Lighting.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/Lighting.cpp.o
.PHONY : src/Lighting.cpp.o

src/Lighting.i: src/Lighting.cpp.i
.PHONY : src/Lighting.i

# target to preprocess a source file
src/Lighting.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/Lighting.cpp.i
.PHONY : src/Lighting.cpp.i

src/Lighting.s: src/Lighting.cpp.s
.PHONY : src/Lighting.s

# target to generate assembly for a file
src/Lighting.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/Lighting.cpp.s
.PHONY : src/Lighting.cpp.s

src/Renderer.o: src/Renderer.cpp.o
.PHONY : src/Renderer.o

# target to build an object file
src/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/Renderer.cpp.o
.PHONY : src/Renderer.cpp.o

src/Renderer.i: src/Renderer.cpp.i
.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s
.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/algorithms/Animation.o: src/algorithms/Animation.cpp.o
.PHONY : src/algorithms/Animation.o

# target to build an object file
src/algorithms/Animation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/algorithms/Animation.cpp.o
.PHONY : src/algorithms/Animation.cpp.o

src/algorithms/Animation.i: src/algorithms/Animation.cpp.i
.PHONY : src/algorithms/Animation.i

# target to preprocess a source file
src/algorithms/Animation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/algorithms/Animation.cpp.i
.PHONY : src/algorithms/Animation.cpp.i

src/algorithms/Animation.s: src/algorithms/Animation.cpp.s
.PHONY : src/algorithms/Animation.s

# target to generate assembly for a file
src/algorithms/Animation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/algorithms/Animation.cpp.s
.PHONY : src/algorithms/Animation.cpp.s

src/algorithms/Clipping.o: src/algorithms/Clipping.cpp.o
.PHONY : src/algorithms/Clipping.o

# target to build an object file
src/algorithms/Clipping.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/algorithms/Clipping.cpp.o
.PHONY : src/algorithms/Clipping.cpp.o

src/algorithms/Clipping.i: src/algorithms/Clipping.cpp.i
.PHONY : src/algorithms/Clipping.i

# target to preprocess a source file
src/algorithms/Clipping.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/algorithms/Clipping.cpp.i
.PHONY : src/algorithms/Clipping.cpp.i

src/algorithms/Clipping.s: src/algorithms/Clipping.cpp.s
.PHONY : src/algorithms/Clipping.s

# target to generate assembly for a file
src/algorithms/Clipping.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/algorithms/Clipping.cpp.s
.PHONY : src/algorithms/Clipping.cpp.s

src/algorithms/Filling.o: src/algorithms/Filling.cpp.o
.PHONY : src/algorithms/Filling.o

# target to build an object file
src/algorithms/Filling.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/algorithms/Filling.cpp.o
.PHONY : src/algorithms/Filling.cpp.o

src/algorithms/Filling.i: src/algorithms/Filling.cpp.i
.PHONY : src/algorithms/Filling.i

# target to preprocess a source file
src/algorithms/Filling.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/algorithms/Filling.cpp.i
.PHONY : src/algorithms/Filling.cpp.i

src/algorithms/Filling.s: src/algorithms/Filling.cpp.s
.PHONY : src/algorithms/Filling.s

# target to generate assembly for a file
src/algorithms/Filling.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/algorithms/Filling.cpp.s
.PHONY : src/algorithms/Filling.cpp.s

src/algorithms/Rasterization.o: src/algorithms/Rasterization.cpp.o
.PHONY : src/algorithms/Rasterization.o

# target to build an object file
src/algorithms/Rasterization.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/algorithms/Rasterization.cpp.o
.PHONY : src/algorithms/Rasterization.cpp.o

src/algorithms/Rasterization.i: src/algorithms/Rasterization.cpp.i
.PHONY : src/algorithms/Rasterization.i

# target to preprocess a source file
src/algorithms/Rasterization.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/algorithms/Rasterization.cpp.i
.PHONY : src/algorithms/Rasterization.cpp.i

src/algorithms/Rasterization.s: src/algorithms/Rasterization.cpp.s
.PHONY : src/algorithms/Rasterization.s

# target to generate assembly for a file
src/algorithms/Rasterization.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/algorithms/Rasterization.cpp.s
.PHONY : src/algorithms/Rasterization.cpp.s

src/algorithms/Shading.o: src/algorithms/Shading.cpp.o
.PHONY : src/algorithms/Shading.o

# target to build an object file
src/algorithms/Shading.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/algorithms/Shading.cpp.o
.PHONY : src/algorithms/Shading.cpp.o

src/algorithms/Shading.i: src/algorithms/Shading.cpp.i
.PHONY : src/algorithms/Shading.i

# target to preprocess a source file
src/algorithms/Shading.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/algorithms/Shading.cpp.i
.PHONY : src/algorithms/Shading.cpp.i

src/algorithms/Shading.s: src/algorithms/Shading.cpp.s
.PHONY : src/algorithms/Shading.s

# target to generate assembly for a file
src/algorithms/Shading.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/algorithms/Shading.cpp.s
.PHONY : src/algorithms/Shading.cpp.s

src/algorithms/Transformations.o: src/algorithms/Transformations.cpp.o
.PHONY : src/algorithms/Transformations.o

# target to build an object file
src/algorithms/Transformations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/algorithms/Transformations.cpp.o
.PHONY : src/algorithms/Transformations.cpp.o

src/algorithms/Transformations.i: src/algorithms/Transformations.cpp.i
.PHONY : src/algorithms/Transformations.i

# target to preprocess a source file
src/algorithms/Transformations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/algorithms/Transformations.cpp.i
.PHONY : src/algorithms/Transformations.cpp.i

src/algorithms/Transformations.s: src/algorithms/Transformations.cpp.s
.PHONY : src/algorithms/Transformations.s

# target to generate assembly for a file
src/algorithms/Transformations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/algorithms/Transformations.cpp.s
.PHONY : src/algorithms/Transformations.cpp.s

src/algorithms/Viewing.o: src/algorithms/Viewing.cpp.o
.PHONY : src/algorithms/Viewing.o

# target to build an object file
src/algorithms/Viewing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/algorithms/Viewing.cpp.o
.PHONY : src/algorithms/Viewing.cpp.o

src/algorithms/Viewing.i: src/algorithms/Viewing.cpp.i
.PHONY : src/algorithms/Viewing.i

# target to preprocess a source file
src/algorithms/Viewing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/algorithms/Viewing.cpp.i
.PHONY : src/algorithms/Viewing.cpp.i

src/algorithms/Viewing.s: src/algorithms/Viewing.cpp.s
.PHONY : src/algorithms/Viewing.s

# target to generate assembly for a file
src/algorithms/Viewing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/algorithms/Viewing.cpp.s
.PHONY : src/algorithms/Viewing.cpp.s

src/algorithms/Visibility.o: src/algorithms/Visibility.cpp.o
.PHONY : src/algorithms/Visibility.o

# target to build an object file
src/algorithms/Visibility.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/algorithms/Visibility.cpp.o
.PHONY : src/algorithms/Visibility.cpp.o

src/algorithms/Visibility.i: src/algorithms/Visibility.cpp.i
.PHONY : src/algorithms/Visibility.i

# target to preprocess a source file
src/algorithms/Visibility.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/algorithms/Visibility.cpp.i
.PHONY : src/algorithms/Visibility.cpp.i

src/algorithms/Visibility.s: src/algorithms/Visibility.cpp.s
.PHONY : src/algorithms/Visibility.s

# target to generate assembly for a file
src/algorithms/Visibility.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/algorithms/Visibility.cpp.s
.PHONY : src/algorithms/Visibility.cpp.s

src/cube/CubeFactory.o: src/cube/CubeFactory.cpp.o
.PHONY : src/cube/CubeFactory.o

# target to build an object file
src/cube/CubeFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/cube/CubeFactory.cpp.o
.PHONY : src/cube/CubeFactory.cpp.o

src/cube/CubeFactory.i: src/cube/CubeFactory.cpp.i
.PHONY : src/cube/CubeFactory.i

# target to preprocess a source file
src/cube/CubeFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/cube/CubeFactory.cpp.i
.PHONY : src/cube/CubeFactory.cpp.i

src/cube/CubeFactory.s: src/cube/CubeFactory.cpp.s
.PHONY : src/cube/CubeFactory.s

# target to generate assembly for a file
src/cube/CubeFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/cube/CubeFactory.cpp.s
.PHONY : src/cube/CubeFactory.cpp.s

src/cube/Cubie.o: src/cube/Cubie.cpp.o
.PHONY : src/cube/Cubie.o

# target to build an object file
src/cube/Cubie.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/cube/Cubie.cpp.o
.PHONY : src/cube/Cubie.cpp.o

src/cube/Cubie.i: src/cube/Cubie.cpp.i
.PHONY : src/cube/Cubie.i

# target to preprocess a source file
src/cube/Cubie.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/cube/Cubie.cpp.i
.PHONY : src/cube/Cubie.cpp.i

src/cube/Cubie.s: src/cube/Cubie.cpp.s
.PHONY : src/cube/Cubie.s

# target to generate assembly for a file
src/cube/Cubie.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/cube/Cubie.cpp.s
.PHONY : src/cube/Cubie.cpp.s

src/cube/Move.o: src/cube/Move.cpp.o
.PHONY : src/cube/Move.o

# target to build an object file
src/cube/Move.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/cube/Move.cpp.o
.PHONY : src/cube/Move.cpp.o

src/cube/Move.i: src/cube/Move.cpp.i
.PHONY : src/cube/Move.i

# target to preprocess a source file
src/cube/Move.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/cube/Move.cpp.i
.PHONY : src/cube/Move.cpp.i

src/cube/Move.s: src/cube/Move.cpp.s
.PHONY : src/cube/Move.s

# target to generate assembly for a file
src/cube/Move.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/cube/Move.cpp.s
.PHONY : src/cube/Move.cpp.s

src/cube/RubiksCube.o: src/cube/RubiksCube.cpp.o
.PHONY : src/cube/RubiksCube.o

# target to build an object file
src/cube/RubiksCube.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/cube/RubiksCube.cpp.o
.PHONY : src/cube/RubiksCube.cpp.o

src/cube/RubiksCube.i: src/cube/RubiksCube.cpp.i
.PHONY : src/cube/RubiksCube.i

# target to preprocess a source file
src/cube/RubiksCube.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/cube/RubiksCube.cpp.i
.PHONY : src/cube/RubiksCube.cpp.i

src/cube/RubiksCube.s: src/cube/RubiksCube.cpp.s
.PHONY : src/cube/RubiksCube.s

# target to generate assembly for a file
src/cube/RubiksCube.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/cube/RubiksCube.cpp.s
.PHONY : src/cube/RubiksCube.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/solver/PatternLibrary.o: src/solver/PatternLibrary.cpp.o
.PHONY : src/solver/PatternLibrary.o

# target to build an object file
src/solver/PatternLibrary.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/solver/PatternLibrary.cpp.o
.PHONY : src/solver/PatternLibrary.cpp.o

src/solver/PatternLibrary.i: src/solver/PatternLibrary.cpp.i
.PHONY : src/solver/PatternLibrary.i

# target to preprocess a source file
src/solver/PatternLibrary.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/solver/PatternLibrary.cpp.i
.PHONY : src/solver/PatternLibrary.cpp.i

src/solver/PatternLibrary.s: src/solver/PatternLibrary.cpp.s
.PHONY : src/solver/PatternLibrary.s

# target to generate assembly for a file
src/solver/PatternLibrary.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/solver/PatternLibrary.cpp.s
.PHONY : src/solver/PatternLibrary.cpp.s

src/solver/ReverseSolver.o: src/solver/ReverseSolver.cpp.o
.PHONY : src/solver/ReverseSolver.o

# target to build an object file
src/solver/ReverseSolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/solver/ReverseSolver.cpp.o
.PHONY : src/solver/ReverseSolver.cpp.o

src/solver/ReverseSolver.i: src/solver/ReverseSolver.cpp.i
.PHONY : src/solver/ReverseSolver.i

# target to preprocess a source file
src/solver/ReverseSolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/solver/ReverseSolver.cpp.i
.PHONY : src/solver/ReverseSolver.cpp.i

src/solver/ReverseSolver.s: src/solver/ReverseSolver.cpp.s
.PHONY : src/solver/ReverseSolver.s

# target to generate assembly for a file
src/solver/ReverseSolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/solver/ReverseSolver.cpp.s
.PHONY : src/solver/ReverseSolver.cpp.s

src/solver/Scrambler.o: src/solver/Scrambler.cpp.o
.PHONY : src/solver/Scrambler.o

# target to build an object file
src/solver/Scrambler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/solver/Scrambler.cpp.o
.PHONY : src/solver/Scrambler.cpp.o

src/solver/Scrambler.i: src/solver/Scrambler.cpp.i
.PHONY : src/solver/Scrambler.i

# target to preprocess a source file
src/solver/Scrambler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/solver/Scrambler.cpp.i
.PHONY : src/solver/Scrambler.cpp.i

src/solver/Scrambler.s: src/solver/Scrambler.cpp.s
.PHONY : src/solver/Scrambler.s

# target to generate assembly for a file
src/solver/Scrambler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/solver/Scrambler.cpp.s
.PHONY : src/solver/Scrambler.cpp.s

src/ui/HUD.o: src/ui/HUD.cpp.o
.PHONY : src/ui/HUD.o

# target to build an object file
src/ui/HUD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/ui/HUD.cpp.o
.PHONY : src/ui/HUD.cpp.o

src/ui/HUD.i: src/ui/HUD.cpp.i
.PHONY : src/ui/HUD.i

# target to preprocess a source file
src/ui/HUD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/ui/HUD.cpp.i
.PHONY : src/ui/HUD.cpp.i

src/ui/HUD.s: src/ui/HUD.cpp.s
.PHONY : src/ui/HUD.s

# target to generate assembly for a file
src/ui/HUD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/ui/HUD.cpp.s
.PHONY : src/ui/HUD.cpp.s

src/ui/Picking.o: src/ui/Picking.cpp.o
.PHONY : src/ui/Picking.o

# target to build an object file
src/ui/Picking.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/ui/Picking.cpp.o
.PHONY : src/ui/Picking.cpp.o

src/ui/Picking.i: src/ui/Picking.cpp.i
.PHONY : src/ui/Picking.i

# target to preprocess a source file
src/ui/Picking.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/ui/Picking.cpp.i
.PHONY : src/ui/Picking.cpp.i

src/ui/Picking.s: src/ui/Picking.cpp.s
.PHONY : src/ui/Picking.s

# target to generate assembly for a file
src/ui/Picking.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/ui/Picking.cpp.s
.PHONY : src/ui/Picking.cpp.s

src/ui/SolutionPlayer.o: src/ui/SolutionPlayer.cpp.o
.PHONY : src/ui/SolutionPlayer.o

# target to build an object file
src/ui/SolutionPlayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/ui/SolutionPlayer.cpp.o
.PHONY : src/ui/SolutionPlayer.cpp.o

src/ui/SolutionPlayer.i: src/ui/SolutionPlayer.cpp.i
.PHONY : src/ui/SolutionPlayer.i

# target to preprocess a source file
src/ui/SolutionPlayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/ui/SolutionPlayer.cpp.i
.PHONY : src/ui/SolutionPlayer.cpp.i

src/ui/SolutionPlayer.s: src/ui/SolutionPlayer.cpp.s
.PHONY : src/ui/SolutionPlayer.s

# target to generate assembly for a file
src/ui/SolutionPlayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/ui/SolutionPlayer.cpp.s
.PHONY : src/ui/SolutionPlayer.cpp.s

src/ui/SolveMode.o: src/ui/SolveMode.cpp.o
.PHONY : src/ui/SolveMode.o

# target to build an object file
src/ui/SolveMode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/ui/SolveMode.cpp.o
.PHONY : src/ui/SolveMode.cpp.o

src/ui/SolveMode.i: src/ui/SolveMode.cpp.i
.PHONY : src/ui/SolveMode.i

# target to preprocess a source file
src/ui/SolveMode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/ui/SolveMode.cpp.i
.PHONY : src/ui/SolveMode.cpp.i

src/ui/SolveMode.s: src/ui/SolveMode.cpp.s
.PHONY : src/ui/SolveMode.s

# target to generate assembly for a file
src/ui/SolveMode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/ui/SolveMode.cpp.s
.PHONY : src/ui/SolveMode.cpp.s

src/ui/WelcomeScreen.o: src/ui/WelcomeScreen.cpp.o
.PHONY : src/ui/WelcomeScreen.o

# target to build an object file
src/ui/WelcomeScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/ui/WelcomeScreen.cpp.o
.PHONY : src/ui/WelcomeScreen.cpp.o

src/ui/WelcomeScreen.i: src/ui/WelcomeScreen.cpp.i
.PHONY : src/ui/WelcomeScreen.i

# target to preprocess a source file
src/ui/WelcomeScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/ui/WelcomeScreen.cpp.i
.PHONY : src/ui/WelcomeScreen.cpp.i

src/ui/WelcomeScreen.s: src/ui/WelcomeScreen.cpp.s
.PHONY : src/ui/WelcomeScreen.s

# target to generate assembly for a file
src/ui/WelcomeScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/ui/WelcomeScreen.cpp.s
.PHONY : src/ui/WelcomeScreen.cpp.s

src/utils/MathUtils.o: src/utils/MathUtils.cpp.o
.PHONY : src/utils/MathUtils.o

# target to build an object file
src/utils/MathUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/utils/MathUtils.cpp.o
.PHONY : src/utils/MathUtils.cpp.o

src/utils/MathUtils.i: src/utils/MathUtils.cpp.i
.PHONY : src/utils/MathUtils.i

# target to preprocess a source file
src/utils/MathUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/utils/MathUtils.cpp.i
.PHONY : src/utils/MathUtils.cpp.i

src/utils/MathUtils.s: src/utils/MathUtils.cpp.s
.PHONY : src/utils/MathUtils.s

# target to generate assembly for a file
src/utils/MathUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/utils/MathUtils.cpp.s
.PHONY : src/utils/MathUtils.cpp.s

src/utils/ScoreManager.o: src/utils/ScoreManager.cpp.o
.PHONY : src/utils/ScoreManager.o

# target to build an object file
src/utils/ScoreManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/utils/ScoreManager.cpp.o
.PHONY : src/utils/ScoreManager.cpp.o

src/utils/ScoreManager.i: src/utils/ScoreManager.cpp.i
.PHONY : src/utils/ScoreManager.i

# target to preprocess a source file
src/utils/ScoreManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/utils/ScoreManager.cpp.i
.PHONY : src/utils/ScoreManager.cpp.i

src/utils/ScoreManager.s: src/utils/ScoreManager.cpp.s
.PHONY : src/utils/ScoreManager.s

# target to generate assembly for a file
src/utils/ScoreManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RubikX3D.dir/build.make CMakeFiles/RubikX3D.dir/src/utils/ScoreManager.cpp.s
.PHONY : src/utils/ScoreManager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RubikX3D"
	@echo "... src/Animation.o"
	@echo "... src/Animation.i"
	@echo "... src/Animation.s"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/Colors.o"
	@echo "... src/Colors.i"
	@echo "... src/Colors.s"
	@echo "... src/Lighting.o"
	@echo "... src/Lighting.i"
	@echo "... src/Lighting.s"
	@echo "... src/Renderer.o"
	@echo "... src/Renderer.i"
	@echo "... src/Renderer.s"
	@echo "... src/algorithms/Animation.o"
	@echo "... src/algorithms/Animation.i"
	@echo "... src/algorithms/Animation.s"
	@echo "... src/algorithms/Clipping.o"
	@echo "... src/algorithms/Clipping.i"
	@echo "... src/algorithms/Clipping.s"
	@echo "... src/algorithms/Filling.o"
	@echo "... src/algorithms/Filling.i"
	@echo "... src/algorithms/Filling.s"
	@echo "... src/algorithms/Rasterization.o"
	@echo "... src/algorithms/Rasterization.i"
	@echo "... src/algorithms/Rasterization.s"
	@echo "... src/algorithms/Shading.o"
	@echo "... src/algorithms/Shading.i"
	@echo "... src/algorithms/Shading.s"
	@echo "... src/algorithms/Transformations.o"
	@echo "... src/algorithms/Transformations.i"
	@echo "... src/algorithms/Transformations.s"
	@echo "... src/algorithms/Viewing.o"
	@echo "... src/algorithms/Viewing.i"
	@echo "... src/algorithms/Viewing.s"
	@echo "... src/algorithms/Visibility.o"
	@echo "... src/algorithms/Visibility.i"
	@echo "... src/algorithms/Visibility.s"
	@echo "... src/cube/CubeFactory.o"
	@echo "... src/cube/CubeFactory.i"
	@echo "... src/cube/CubeFactory.s"
	@echo "... src/cube/Cubie.o"
	@echo "... src/cube/Cubie.i"
	@echo "... src/cube/Cubie.s"
	@echo "... src/cube/Move.o"
	@echo "... src/cube/Move.i"
	@echo "... src/cube/Move.s"
	@echo "... src/cube/RubiksCube.o"
	@echo "... src/cube/RubiksCube.i"
	@echo "... src/cube/RubiksCube.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/solver/PatternLibrary.o"
	@echo "... src/solver/PatternLibrary.i"
	@echo "... src/solver/PatternLibrary.s"
	@echo "... src/solver/ReverseSolver.o"
	@echo "... src/solver/ReverseSolver.i"
	@echo "... src/solver/ReverseSolver.s"
	@echo "... src/solver/Scrambler.o"
	@echo "... src/solver/Scrambler.i"
	@echo "... src/solver/Scrambler.s"
	@echo "... src/ui/HUD.o"
	@echo "... src/ui/HUD.i"
	@echo "... src/ui/HUD.s"
	@echo "... src/ui/Picking.o"
	@echo "... src/ui/Picking.i"
	@echo "... src/ui/Picking.s"
	@echo "... src/ui/SolutionPlayer.o"
	@echo "... src/ui/SolutionPlayer.i"
	@echo "... src/ui/SolutionPlayer.s"
	@echo "... src/ui/SolveMode.o"
	@echo "... src/ui/SolveMode.i"
	@echo "... src/ui/SolveMode.s"
	@echo "... src/ui/WelcomeScreen.o"
	@echo "... src/ui/WelcomeScreen.i"
	@echo "... src/ui/WelcomeScreen.s"
	@echo "... src/utils/MathUtils.o"
	@echo "... src/utils/MathUtils.i"
	@echo "... src/utils/MathUtils.s"
	@echo "... src/utils/ScoreManager.o"
	@echo "... src/utils/ScoreManager.i"
	@echo "... src/utils/ScoreManager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

